version: 2.1
orbs:
    node: circleci/node@4.7.0
jobs:
  build:
       working_directory: ~/SoftwareEngineering-5
       docker:
         - image: cimg/node:lts
       steps:
         - checkout:
            path: ~/
         - run: npm install
